In [232]:
import pandas as pd

In [233]:
amazon_prime = pd.read_csv('Datasets/amazon_prime_titles.csv',delimiter = ',',encoding = "utf-8")

In [234]:
disney_plus = pd.read_csv('Datasets/disney_plus_titles.csv',delimiter = ',',encoding = "utf-8")

In [235]:
hulu = pd.read_csv('Datasets/hulu_titles.csv',delimiter = ',',encoding = "utf-8")

In [236]:
netflix = pd.read_json('Datasets/netflix_titles.json')

In [237]:
#copy dataframes to maintain original versions
amz = amazon_prime.copy()
dis = disney_plus.copy()
hu = hulu.copy()
net = netflix.copy()

In [238]:
amz.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8138,s8139,Movie,Ed Gein: The Butcher of Plainfield,Michael Feifer,"Kane Hodder, Michael Berryman, Priscilla Barnes",NaN,NaN,2007,R,90 min,Horror,The story of one of America's most well-known ...
8110,s8111,Movie,Nick Cannon: Mr. Showbiz,Jay Karas,Nick Cannon,NaN,NaN,2011,18+,58 min,"Arts, Entertainment, and Culture, Comedy, Spec...","In his first comedy special, the popular comic..."
4861,s4862,Movie,15 Minute Forest Stream Meditation,Mark Knight,Marie-Anne Newland,NaN,NaN,2020,ALL,15 min,Special Interest,Guided Meditation by Anne-Marie Newland accomp...
5510,s5511,Movie,Dickie Roberts: Former Child Star,Sam Weisman,"David Spade, Alyssa Milano, Mary McCormack, Ro...",NaN,NaN,2003,PG-13,98 min,Comedy,"Desperate to revive his career, Dickie tries t..."
8309,s8310,Movie,I Am Bolt,"Benjamin Turner, Gabe Turner",Usain Bolt,NaN,NaN,2016,NR,103 min,Documentary,"Fully authorized, access-all-areas feature doc..."

In [239]:
dis.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
141,s142,TV Show,Cesar Millan: Better Human Better Dog,NaN,Dustin Rubin,NaN,"August 4, 2021",2021,TV-14,1 Season,"Animals & Nature, Docuseries, Family",Renowned Dog Behaviorist Cesar Millan transfor...
448,s449,Movie,Big Cat Games,Jeremy Turner,Boone Smith,NaN,"July 31, 2020",2015,TV-PG,44 min,"Animals & Nature, Family, Reality","Boone Smith hosts a feline showdown as lion, t..."
292,s293,TV Show,Pair of Kings,NaN,"Mitchel Musso, Doc Shaw, Kelsey Chow, Ryan Och...",United States,"February 26, 2021",2010,TV-Y7,3 Seasons,"Action-Adventure, Comedy, Coming of Age","Fraternal teenage twins, Brady and Boomer, are..."
1131,s1132,Movie,Pirates of the Caribbean: At World's End,Gore Verbinski,"Johnny Depp, Orlando Bloom, Keira Knightley, S...",United States,"November 12, 2019",2007,PG-13,169 min,"Action-Adventure, Fantasy",An alliance forms to rescue Captain Jack Sparr...
1058,s1059,TV Show,Marvel's Guardians of the Galaxy (Series),NaN,"Will Friedle, Trevor Devall, Kevin Richardson,...",United States,"November 12, 2019",2015,TV-Y7,3 Seasons,"Action-Adventure, Animation, Kids",The Guardians find a map leading to a powerful...

In [240]:
hu.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2049,s2050,Movie,Ride,NaN,NaN,United States,"October 2, 2019",2019,7 min,NaN,Horror,Spin classes can be a bit intimidating. But fo...
872,s873,TV Show,Staged,NaN,NaN,NaN,"March 16, 2021",2020,NaN,2 Seasons,"Comedy, Drama, International",David Tennant and Michael Sheen star as two ac...
1095,s1096,Movie,Soldiers of Fortune,NaN,NaN,"Russia, United States","December 25, 2020",2012,R,94 min,"Action, Adventure, Thriller",A former Special Forces soldier (Christian Sla...
2574,s2575,TV Show,Cold Case Files,NaN,NaN,United States,"January 1, 2018",2009,TV-14,1 Season,"Crime, Documentaries",The series examines each piece of forensic evi...
1088,s1089,Movie,The Limehouse Golem,NaN,NaN,United Kingdom,"December 30, 2020",2017,109 min,NaN,"Crime, Mystery, Thriller",With the Limehouse Golem serial killer on the ...

In [241]:
net.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6791,s6792,TV Show,Four Seasons in Havana,None,"Jorge Perugorría, Carlos Enrique Almirante, Ma...","Spain, Cuba","December 9, 2016",2016,TV-MA,1 Season,"Crime TV Shows, International TV Shows, Spanis...","As Havana slowly revolves through the year, wi..."
513,s514,TV Show,Colony,None,"Josh Holloway, Sarah Wayne Callies, Peter Jaco...",United States,"July 6, 2021",2018,TV-14,3 Seasons,"TV Action & Adventure, TV Dramas, TV Sci-Fi & ...",When LA is invaded by outside forces and becom...
112,s113,Movie,Worth,Sara Colangelo,"Michael Keaton, Stanley Tucci, Amy Ryan, Shuno...",None,"September 3, 2021",2021,PG-13,119 min,Dramas,"In the wake of the Sept. 11 attacks, a lawyer ..."
2107,s2108,Movie,The Sleepover,Trish Sie,"Sadie Stanley, Maxwell Simkins, Ken Marino, Ma...",United States,"August 21, 2020",2020,TV-PG,104 min,"Action & Adventure, Children & Family Movies, ...",What do you do if your parents are kidnapped b...
6637,s6638,Movie,Doubt,John Patrick Shanley,"Meryl Streep, Philip Seymour Hoffman, Amy Adam...",United States,"March 7, 2019",2008,PG-13,104 min,"Dramas, Faith & Spirituality",Sister Aloysius begins to have doubts about do...

In [242]:
amz.isnull().sum()

show_id            0
type               0
title              0
director        2082
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [243]:
dis.isnull().sum()

show_id           0
type              0
title             0
director        473
cast            190
country         219
date_added        3
release_year      0
rating            3
duration          0
listed_in         0
description       0
dtype: int64

In [244]:
hu.isnull().sum()

show_id            0
type               0
title              0
director        3070
cast            3073
country         1453
date_added        28
release_year       0
rating           520
duration         479
listed_in          0
description        4
dtype: int64

In [245]:
net.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [246]:
#drop columns we dont need for client requisitions
amz.drop(columns=['director','description', 'rating', 'director'], inplace=True)
dis.drop(columns=['director', 'description', 'rating', 'director'], inplace=True)
hu.drop(columns=['director', 'description', 'rating', 'director'], inplace=True)
net.drop(columns=['director', 'description', 'rating', 'director'], inplace=True)

In [247]:
#fill null values
net.fillna('no data', inplace=True)
amz.fillna('no data', inplace=True)
dis.fillna('no data', inplace=True)
hu.fillna('no data', inplace=True)

In [248]:
net.isnull().sum()

show_id         0
type            0
title           0
cast            0
country         0
date_added      0
release_year    0
duration        0
listed_in       0
dtype: int64

In [249]:
hu.isnull().sum()

show_id         0
type            0
title           0
cast            0
country         0
date_added      0
release_year    0
duration        0
listed_in       0
dtype: int64

In [250]:
dis.isnull().sum()

show_id         0
type            0
title           0
cast            0
country         0
date_added      0
release_year    0
duration        0
listed_in       0
dtype: int64

In [251]:
amz.isnull().sum()

show_id         0
type            0
title           0
cast            0
country         0
date_added      0
release_year    0
duration        0
listed_in       0
dtype: int64

In [252]:
#add column that id's what platform each movie/tvshow is from
amz['platform'] = 'amazon prime'
net['platform'] = 'netflix'
hu['platform'] = 'hulu'
dis['platform'] = 'disney plus'

In [253]:
#split duration into two columns, discriminating by string contents: either 'min' or 'seaons'
amz['movie_duration_mins']=amz['duration'].apply( lambda i: i.split()[0] if i.split()[1]=='min' else '0')
amz['seasons']=amz['duration'].apply( lambda i: i.split()[0] if i.split(" ",1)[1]=='Seasons' or i.split(" ",1)[1]=='Season' else '0')

In [254]:
net['movie_duration_mins']=net['duration'].apply( lambda i: i.split()[0] if i.split()[1]=='min' else '0')
net['seasons']=net['duration'].apply( lambda i: i.split()[0] if i.split(" ",1)[1]=='Seasons' or i.split(" ",1)[1]=='Season' else '0')

In [255]:
hu['movie_duration_mins']=hu['duration'].apply( lambda i: i.split()[0] if i.split()[1]=='min' else '0')
hu['seasons']=hu['duration'].apply( lambda i: i.split()[0] if i.split(" ",1)[1]=='Seasons' or i.split(" ",1)[1]=='Season' else '0')

In [256]:
dis['movie_duration_mins']=dis['duration'].apply( lambda i: i.split()[0] if i.split()[1]=='min' else '0')
dis['seasons']=dis['duration'].apply( lambda i: i.split()[0] if i.split(" ",1)[1]=='Seasons' or i.split(" ",1)[1]=='Season' else '0')

In [257]:
#concatenate all dfs into one in order to run querys
content = pd.concat([amz, net, hu, dis], axis=0)

In [258]:
content.drop(columns=['duration'], inplace=True)

In [308]:
content.sample(10)

,show_id,type,title,cast,country,date_added,release_year,listed_in,platform,movie_duration_mins,seasons
3293,s3294,TV Show,Little Things,"Dhruv Sehgal, Mithila Palkar",India,"November 9, 2019",2019,"International TV Shows, Romantic TV Shows, TV ...",netflix,0,3
832,s833,Movie,Sye Raa Narasimha Reddy (Hindi),"Chiranjeevi, Amitabh Bachchan, Sudeep, Jagapat...",no data,no data,2019,Action,amazon prime,170,0
1344,s1345,Movie,Monsterland,no data,United States,"October 2, 2020",2020,Horror,hulu,0,0
866,s867,Movie,Doug's 1st Movie,"Thomas McHugh, Fred Newman, Chris Phillips, Co...",United States,"November 12, 2019",1999,"Animation, Comedy, Family",disney plus,80,0
6956,s6957,Movie,Hell or High Water,"Jeff Bridges, Chris Pine, Ben Foster, Gil Birm...",United States,"January 1, 2019",2016,"Dramas, Independent Movies",netflix,102,0
1598,s1599,Movie,Destiny in Space,no data,"Canada, United States","June 11, 2020",1994,"Documentaries, Kids",hulu,0,0
1360,s1361,Movie,Three Blind Mouseketeers,"Pinto Colvig, Billy Bletcher",United States,"November 12, 2019",1936,"Animation, Family, Parody",disney plus,9,0
3498,s3499,TV Show,2019 AVP Hermosa Beach Open - Day 3,no data,no data,no data,2019,TV Shows,amazon prime,0,1
1569,s1570,TV Show,Masameer Classics,"Malik Nejer, Abdulaziz Alshehri",Saudi Arabia,"December 9, 2020",2013,"International TV Shows, TV Comedies",netflix,0,4
138,s139,Movie,Beverly Hills Chihuahua 3: Viva La Fiesta!,"George Lopez, Odette Annable, Ernie Hudson, Mi...",United States,"August 6, 2021",2012,"Comedy, Coming of Age, Family",disney plus,92,0

In [260]:
content.dtypes

show_id                object
type                   object
title                  object
cast                   object
country                object
date_added             object
release_year            int64
listed_in              object
platform               object
movie_duration_mins    object
seasons                object
dtype: object

In [261]:
#change dtype to int for seasons and duration (mins)
content = content.astype({'seasons' : 'int'})
content = content.astype({'movie_duration_mins' : 'int'})

In [262]:
content.dtypes

show_id                object
type                   object
title                  object
cast                   object
country                object
date_added             object
release_year            int64
listed_in              object
platform               object
movie_duration_mins     int64
seasons                 int64
dtype: object

In [263]:
content.to_csv('content_global.csv')